FROM nvidia/cuda:12.9.1-cudnn-runtime-ubuntu24.04

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3-dev build-essential ffmpeg && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

COPY . .

RUN uv sync --compile-bytecode

ENTRYPOINT [ "uv" ] 
CMD ["run", "src/main.py"]