FROM ghcr.io/astral-sh/uv:debian

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3-dev build-essential ffmpeg && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

COPY . .

RUN uv sync --compile-bytecode

ENTRYPOINT [ "uv" ] 
CMD ["run", "src/main.py"]